name: 'review-manager'
description: 'Manage code reviews for your PRs'
inputs:
  token:
    required: true
  min_approving_reviews_total:
    description: 'Min number of total approving reviews for success'
    required: false
    default: 2
  min_approving_reviews_per_area:
    description: 'Min number of approving reviews for each area label'
    required: false
    default: 1
  area_ownership_file:
    description: 'Repository file which includes the owners for each area label'
    required: true
    default: '.github/AREA-OWNERS'
  fail_if_missing_approving_reviews:
    description: 'Fail action if there are not enough approving reviews'
    required: false
    default: false
  label_on_success:
    description: 'Label the PR with this label if there are enough approving reviews'
    required: false
    default: ''
  fail_if_no_area_label:
    description: 'If the PR is not labelled with any label from the ownership file, fail'
    required: false
    default: true
  succeed_if_maintainer_approves:
    description: 'Automatically succeeds if a maintainer left an approving review'
    required: false
    default: false
  maintainers_are_universal_approvers:
    description: 'Maintainers can provide an approving review for each area label'
    required: false
    default: false
  ignore_if_not_labelled_with:
    description: 'Ignore all PRs not labelled with this label'
    required: false
    default: ''
  fail_if_not_enough_available_approvers_for_area:
    description: 'Fail if there are not enough available reviewers (< min_approving_reviews_per_area) defined for a given area'
    required: false
    default: false
  support_label_regex:
    description: 'Support regexes for labels in ownership file'
    required: false
    default: true
  request_reviews_from_maintainers_if_needed:
    description: 'If an area label does not have enough approvers, request reviews from maintainers'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
